"""Reciprocal Rank Fusion for hybrid search.

Combines results from dense vector search and BM25 sparse search
using weighted Reciprocal Rank Fusion (RRF) to produce a unified ranking.
Numerical queries automatically boost table/XBRL chunk scores.
"""

import logging
import re
from collections import defaultdict
from typing import Optional

from src.retrieval.bm25_search import BM25Index
from src.retrieval.models import RetrievalConfig, SearchResult
from src.retrieval.reranker import Reranker
from src.retrieval.vector_store import ChromaStore

logger = logging.getLogger(__name__)

_NUMERICAL_PATTERNS = [
    r"\d+",
    r"how much",
    r"how many",
    r"what was the",
    r"what is the",
    r"revenue",
    r"earnings",
    r"income",
    r"profit",
    r"ebitda",
    r"eps",
    r"margin",
    r"ratio",
    r"debt",
    r"assets",
    r"liabilities",
    r"cash flow",
    r"growth",
    r"compare",
    r"year over year",
    r"yoy",
    r"\$",
    r"%",
]

_NUMERICAL_RE = re.compile("|".join(_NUMERICAL_PATTERNS), re.IGNORECASE)
_TABLE_BOOST = 1.5


class HybridRetriever:
    """Combines vector and BM25 search results via weighted Reciprocal Rank Fusion.

    Args:
        vector_store: ChromaStore instance for dense retrieval.
        bm25_index: BM25Index instance for sparse retrieval.
        config: RetrievalConfig with top_k, weights, and filters.
    """

    _SECTION_ROUTING: dict[str, list[str]] = {
        r"balance sheet|assets|liabilities|equity|stockholders": ["Item 8"],
        r"risk|risk factor": ["Item 1A"],
        r"revenue|income|margin|earnings|profit|operat": ["Item 7", "Item 8"],
        r"business|overview|strategy|product|segment": ["Item 1"],
        r"market risk|interest rate|currency|foreign exchange": ["Item 7A"],
        r"cash flow|liquidity|capital": ["Item 7", "Item 8"],
    }

    _SECTION_BOOST = 1.3

    _FINANCIAL_SYNONYMS: dict[str, list[str]] = {
        "revenue": ["net sales", "total revenue", "net revenue"],
        "earnings": ["net income", "net earnings", "profit"],
        "profit": ["net income", "operating income", "gross profit"],
        "debt": ["liabilities", "borrowings", "long-term debt"],
        "assets": ["total assets", "current assets"],
        "cash flow": ["operating cash flow", "cash from operations", "cash generated by operating"],
        "eps": ["earnings per share"],
        "r&d": ["research and development"],
        "sg&a": ["selling general and administrative"],
        "capex": ["capital expenditures"],
        "stockholders equity": ["shareholders equity", "total equity"],
        "cost of revenue": ["cost of goods sold", "cogs"],
    }

    @staticmethod
    def _expand_query(query: str) -> str:
        """Expand query with financial synonym terms.

        Scans the query for known financial terms and appends their
        synonyms joined with ' OR ' to broaden retrieval coverage.

        Args:
            query: Original query string.

        Returns:
            Expanded query with synonym terms appended, or the
            original query if no synonyms match.
        """
        query_lower = query.lower()
        expansions: list[str] = []
        for term, synonyms in HybridRetriever._FINANCIAL_SYNONYMS.items():
            if term in query_lower:
                expansions.extend(synonyms)
        if expansions:
            return query + " OR " + " OR ".join(expansions)
        return query

    @staticmethod
    def _detect_target_sections(query: str) -> list[str]:
        """Detect SEC filing sections relevant to the query.

        Args:
            query: Natural language query string.

        Returns:
            List of section prefixes (e.g., ["Item 7", "Item 8"]).
        """
        sections: set[str] = set()
        for pattern, targets in HybridRetriever._SECTION_ROUTING.items():
            if re.search(pattern, query, re.IGNORECASE):
                sections.update(targets)
        return sorted(sections)

    def __init__(
        self,
        vector_store: ChromaStore,
        bm25_index: BM25Index,
        config: RetrievalConfig | None = None,
        reranker: Reranker | None = None,
    ) -> None:
        """Initialize the hybrid retriever."""
        self._vector_store = vector_store
        self._bm25_index = bm25_index
        self._config = config or RetrievalConfig()
        self._reranker = reranker
        self._rrf_k = 60

    @staticmethod
    def _is_numerical_query(query: str) -> bool:
        """Detect whether a query is numerical/quantitative.

        Returns True when two or more numerical signal patterns match.
        """
        return len(_NUMERICAL_RE.findall(query)) >= 2

    def search(
        self,
        query: str,
        filters: Optional[dict] = None,
    ) -> list[SearchResult]:
        """Run hybrid retrieval with RRF fusion and numerical boosting.

        Args:
            query: Natural language query string.
            filters: Optional metadata filters forwarded to the vector store.

        Returns:
            Fused list of SearchResult objects ranked by RRF score.
        """
        cfg = self._config
        effective_filters = filters or cfg.filters

        expanded_query = self._expand_query(query)

        dense_results = self._vector_store.search(
            query, top_k=cfg.top_k, filters=effective_filters
        )
        sparse_results = self._bm25_index.search(expanded_query, top_k=cfg.top_k)

        fused = self._rrf_fuse(
            dense_results, sparse_results, cfg.dense_weight, cfg.sparse_weight
        )

        if self._is_numerical_query(query):
            fused = [
                r.model_copy(update={"score": r.score * _TABLE_BOOST})
                if r.metadata.is_table
                else r
                for r in fused
            ]
            fused.sort(key=lambda r: r.score, reverse=True)

        # Query-type section boosting
        target_sections = self._detect_target_sections(query)
        if target_sections:
            fused = [
                r.model_copy(update={"score": r.score * self._SECTION_BOOST})
                if any(r.metadata.section_name.startswith(s) for s in target_sections)
                else r
                for r in fused
            ]
            fused.sort(key=lambda r: r.score, reverse=True)

        # Cross-encoder reranking
        if self._reranker is not None:
            results = self._reranker.rerank(query, fused, cfg.rerank_top_k)
        else:
            results = fused[: cfg.top_k]

        return results

    def _rrf_fuse(
        self,
        dense_results: list[SearchResult],
        sparse_results: list[SearchResult],
        dense_weight: float,
        sparse_weight: float,
    ) -> list[SearchResult]:
        """Reciprocal Rank Fusion: score = sum(weight / (k + rank))."""
        scores: dict[str, float] = defaultdict(float)
        docs: dict[str, SearchResult] = {}

        for rank, result in enumerate(dense_results, start=1):
            scores[result.chunk_id] += dense_weight / (self._rrf_k + rank)
            if (
                result.chunk_id not in docs
                or result.score > docs[result.chunk_id].score
            ):
                docs[result.chunk_id] = result

        for rank, result in enumerate(sparse_results, start=1):
            scores[result.chunk_id] += sparse_weight / (self._rrf_k + rank)
            if (
                result.chunk_id not in docs
                or result.score > docs[result.chunk_id].score
            ):
                docs[result.chunk_id] = result

        return [
            docs[cid].model_copy(update={"score": scores[cid], "source": "hybrid"})
            for cid in sorted(scores, key=lambda cid: scores[cid], reverse=True)
        ]
